name: Build & Proof-Check

on: [push, pull_request]

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.19'
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-finger-tree.opam'
          custom_image: ${{ matrix.image }}
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "Build project"
              opam exec -- make -j 2
            endGroup
            startGroup "Audit: Print Assumptions + Admitted/Axiom sweep"
              opam exec -- make audit
            endGroup
          # the default uninstall step expects the package to have been
          # installed by the default script, which we override above
          uninstall: ''

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
